function j = Jacob(t_vec)

    t1 = t_vec(1);
    t2 = t_vec(2);
    t3 = t_vec(3);
    t4 = t_vec(4);

    a3 = 35.92;
    d5 = 36.88;

    %cos(t1)*cos(t2)*cos(t3)*sin(t4)*d5 ...
    %        + sin(t1)*sin(t3)*sin(t4)*d5 ...
    %        - cos(t1)*sin(t2)*cos(t4)*d5 ...
    %        + cos(t1)*cos(t2)*cos(t3)*a3 ...
    %        + sin(t1)*sin(t3)*a3;

    
    
    
   dx_dt1 = - sin(t1)*cos(t2)*cos(t3)*sin(t4)*d5 ...
            + cos(t1)*sin(t3)*sin(t4)*d5 ...
            + sin(t1)*sin(t2)*cos(t4)*d5 ...
            - sin(t1)*cos(t2)*cos(t3)*a3 ...
            + cos(t1)*sin(t3)*a3;

   dx_dt2 = - cos(t1)*sin(t2)*cos(t3)*sin(t4)*d5 ...
            - cos(t1)*cos(t2)*cos(t4)*d5 ...
            - cos(t1)*sin(t2)*cos(t3)*a3;
        
   dx_dt3 = - cos(t1)*cos(t2)*sin(t3)*sin(t4)*d5 ...
            + sin(t1)*cos(t3)*sin(t4)*d5 ...
            - cos(t1)*cos(t2)*sin(t3)*a3 ...
            + sin(t1)*cos(t3)*a3; 
        
   dx_dt4 = cos(t1)*cos(t2)*cos(t3)*cos(t4)*d5 ...
            + sin(t1)*sin(t3)*cos(t4)*d5 ...
            + cos(t1)*sin(t2)*sin(t4)*d5;
        
   y = sin(t1)*cos(t2)*cos(t3)*sin(t4)*d5...
       - cos(t1)*cos(t2)*sin(t4)*d5 ...
       - sin(t1)*sin(t2)*cos(t4)*d5 ...
       + sin(t1)*cos(t2)*cos(t3)*a3 ...
       - cos(t1)*cos(t2)*a3;
   
   dy_dt1 = cos(t1)*cos(t2)*cos(t3)*sin(t4)*d5...
       + sin(t1)*cos(t2)*sin(t4)*d5 ...
       - cos(t1)*sin(t2)*cos(t4)*d5 ...
       + cos(t1)*cos(t2)*cos(t3)*a3 ...
       + sin(t1)*cos(t2)*a3;
   
   dy_dt2 = - sin(t1)*sin(t2)*cos(t3)*sin(t4)*d5...
       + cos(t1)*sin(t2)*sin(t4)*d5 ...
       - sin(t1)*cos(t2)*cos(t4)*d5 ...
       - sin(t1)*sin(t2)*cos(t3)*a3 ...
       + cos(t1)*sin(t2)*a3;
   
   dy_dt3 = -sin(t1)*cos(t2)*sin(t3)*sin(t4)*d5...
       - sin(t1)*cos(t2)*sin(t3)*a3;
   
   dy_dt4 = sin(t1)*cos(t2)*cos(t3)*cos(t4)*d5...
       - cos(t1)*cos(t2)*cos(t4)*d5 ...
       + sin(t1)*sin(t2)*sin(t4)*d5;
        
   %  z =      sin(t2)*cos(t3)*sin(t4)*d5 ...
   %         + cos(t2)*cos(t4)*d5 ...
   %         + sin(t2)*cos(t3)*a3;
   
   dz_dt1 = 0;
   
   dz_dt2 = cos(t2)*cos(t3)*sin(t4)*d5 ...
            - sin(t2)*cos(t4)*d5 ...
            + cos(t2)*cos(t3)*a3;
        
   dz_dt3 = - sin(t2)*sin(t3)*sin(t4)*d5 ...
            - sin(t2)*sin(t3)*a3;
        
   dz_dt4 = sin(t2)*cos(t3)*cos(t4)*d5 ...
            - cos(t2)*sin(t4)*d5;
        
   j = [dx_dt1 dx_dt2 dx_dt3 dx_dt4;
        dy_dt1 dy_dt2 dy_dt3 dy_dt4;
        dz_dt1 dz_dt2 dz_dt3 dz_dt4]; 
end